"""
Django settings for Suite project.

Generated by 'django-admin startproject' using Django 4.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

from graphql_auth.settings import GraphQLAuthSettings

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(7%+v(0@z&z&p+@o5qhvn3am8f8t_3t=e(qi#$k!um-til8(07'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # .....Apps
    'Espannol.boxeo.apps.BoxeoConfig',
    'Espannol.deportista.apps.DeportistaConfig',
    'graphene_app.apps.GrapheneAppConfig',
    'Espannol.nomencladores.apps.NomencladoresConfig',
    'Espannol.seguridad.apps.SeguridadConfig',
    "Espannol.Deportes.apps.DeportesConfig",
    # .....modulos
    'graphene_django',
    'graphql_jwt.refresh_token.apps.RefreshTokenConfig',
    'graphql_auth',
    'corsheaders',
    "graphene_file_upload",
    "rest_framework",
    "Espannol.pruebas.apps.PruebasConfig"
#     "Ruso.boxeo_ruso.apps.BoxeoRusoConfig",
#     "Ingles.boxeo_ingles.apps.BoxeoInglesConfig",
#     "Frances.boxeo_frances.apps.BoxeoFrancesConfig",
#     "Frances.Deportes_frances.apps.DeportesFrancesConfig",
#     "Ingles.Deportes_ingles.apps.DeportesInglesConfig",
#     "Ruso.Deportes_ruso.apps.DeportesRusoConfig",
#     "Frances.deportista_frances.apps.DeportistaFrancesConfig",
#     "Ingles.deportista_ingles.apps.DeportistaInglesConfig",
#     "Ruso.deportista_ruso.apps.DeportistaRusoConfig",
#     "Ruso.nomencladores_ruso.apps.NomencladoresRusoConfig",
#     "Ingles.nomencladores_ingles.apps.NomencladoresInglesConfig",
#     "Frances.nomencladores_frances.apps.NomencladoresFrancesConfig",
#     "Frances.pruebas_frances.apps.PruebasFrancesConfig",
#     "Ingles.pruebas_ingles.apps.PruebasInglesConfig",
#     "Ruso.pruebas_ruso.apps.PruebasRusoConfig",
#     "Ingles.seguridad_ingles.apps.SeguridadInglesConfig",
#     "Frances.seguridad_frances.apps.SeguridadFrancesConfig",
#     "seguridad_ruso.apps.SeguridadRusoConfig"
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Suite.urls'
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = ['http://localhost:8080', 'http://127.0.0.1:8000', 'http://localhost:8000']
CORS_ORIGIN_WHITELIST = ['http://localhost:8080', 'http://127.0.0.1:8000', 'http://localhost:8000']
CORS_ALLOW_CREDENTIALS = True
APPEND_SLASH = True
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Suite.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'suite',
#         'USER': 'postgres',
#         'PASSWORD': 'postgres',
#         'HOST': 'pgsql-15.4.1',
#         'PORT': '5432',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'suite',
        'USER': 'postgres',
        'PASSWORD': 'postgres',
        'HOST': 'localhost',
        'PORT': '5433',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-es'
from django.conf.locale.en import formats as en_formats

en_formats.SHORT_DATETIME_FORMAT = "d/m/y | P"
en_formats.SHORT_DATE_FORMAT = "d/m/y"

TIME_ZONE = 'America/Tijuana'

USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media_root/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media_root")
STATIC_ROOT = os.path.join(BASE_DIR, "static_root")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
AUTH_USER_MODEL = 'seguridad.ExtendUser'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
GRAPHENE = {
    'SCHEMA': 'graphene_app.schema.schema',
    'MIDDLEWARE': [
        "graphql_jwt.middleware.JSONWebTokenMiddleware",
    ],
}

AUTHENTICATION_BACKENDS = [
    # "graphql_jwt.backends.JSONWebTokenBackend",
    'graphql_auth.backends.GraphQLAuthBackend',
    "django.contrib.auth.backends.ModelBackend",
]
GRAPHQL_JWT = {
    "JWT_ALLOW_ANY_CLASSES": [
        "graphql_auth.mutations.Register",
        "graphql_auth.mutations.VerifyAccount",
        "graphql_auth.mutations.ResendActivationEmail",
        "graphql_auth.mutations.SendPasswordResetEmail",
        "graphql_auth.mutations.PasswordReset",
        "graphql_auth.mutations.ObtainJSONWebToken",
        "graphql_auth.mutations.VerifyToken",
        "graphql_auth.mutations.RefreshToken",
        "graphql_auth.mutations.RevokeToken",
    ],
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LONG_RUNNING_REFRESH_TOKEN': True,
}
REGISTER_MUTATION_FIELDS = ["email", "username"]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
