# Generated by Django 3.2.19 on 2024-04-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boxeo', '0003_auto_20240326_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='codifresultado',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='configgolpe',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='golpe',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='idioma',
        ),
    ]
