# Generated by Django 3.2.19 on 2024-04-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxeo', '0004_auto_20240415_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='idioma',
            field=models.CharField(default='es', max_length=255, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='codifresultado',
            name='idioma',
            field=models.CharField(default='es', max_length=255, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='combate',
            name='idioma',
            field=models.CharField(default='es', max_length=255, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='golpe',
            name='idioma',
            field=models.CharField(default='es', max_length=255, verbose_name='Idioma'),
        ),
    ]
