# Generated by Django 3.2.19 on 2024-04-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxeo', '0006_auto_20240417_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='peso_max',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='peso_min',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
