# Generated by Django 3.2.19 on 2024-02-26 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deportista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=255, unique=True, verbose_name='Categoría')),
                ('peso_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso_max', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='CodifResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resul', models.CharField(max_length=255, verbose_name='resultado')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'codifresultado',
                'verbose_name_plural': 'codifresultados',
                'db_table': 'codifresultado',
            },
        ),
        migrations.CreateModel(
            name='Combate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'combate',
                'verbose_name_plural': 'combates',
                'db_table': 'combate',
            },
        ),
        migrations.CreateModel(
            name='Golpe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golpe', models.CharField(max_length=255, verbose_name='golpe')),
                ('siglas', models.CharField(blank=True, max_length=10, null=True, verbose_name='siglas')),
                ('efectivo', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'verbose_name': 'golpe',
                'verbose_name_plural': 'golpes',
                'db_table': 'golpe',
            },
        ),
        migrations.CreateModel(
            name='Pugil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.CharField(max_length=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boxeo.categoria')),
                ('deportista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deportista.deportista')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boxeo.combate')),
                ('pugil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boxeo.pugil')),
                ('resultado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boxeo.codifresultado')),
            ],
            options={
                'verbose_name': 'resultado',
                'verbose_name_plural': 'resultados',
                'db_table': 'resultado',
            },
        ),
        migrations.CreateModel(
            name='ContadorGolpes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asalto', models.PositiveIntegerField()),
                ('tiempo', models.CharField(blank=True, max_length=6, null=True)),
                ('combate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boxeo.combate')),
                ('esquina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boxeo.pugil', verbose_name='esquina')),
                ('golpe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boxeo.golpe')),
            ],
            options={
                'verbose_name': 'contadorgolpe',
                'verbose_name_plural': 'contadorgolpes',
                'db_table': 'contador_golpe',
            },
        ),
        migrations.CreateModel(
            name='ConfigGolpe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecla', models.CharField(max_length=255, verbose_name='tecla')),
                ('golpe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boxeo.golpe')),
            ],
            options={
                'verbose_name': 'configolpe',
                'verbose_name_plural': 'configolpes',
                'db_table': 'config_golpe',
            },
        ),
    ]
