# Generated by Django 3.2.19 on 2024-02-26 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0001_initial'),
        ('deportista', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='codigo',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='deportista',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Deportes.disciplina'),
        ),
    ]
