# Generated by Django 3.2.19 on 2024-02-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportista', '0002_auto_20240226_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='sexo',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
