# Generated by Django 3.2.19 on 2024-03-06 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0003_alter_disciplina_deporte'),
        ('deportista', '0007_auto_20240305_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='deporte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Deportes.deporte'),
        ),
    ]
