# Generated by Django 3.2.19 on 2024-03-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportista', '0008_deportista_deporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='codigo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
