# Generated by Django 3.2.19 on 2024-02-28 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_auto_20240228_1426'),
        ('deportista', '0003_deportista_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='deportista',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deportista',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='seguridad.provincia'),
        ),
    ]
