# Generated by Django 3.2.19 on 2024-02-29 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0003_alter_disciplina_deporte'),
        ('deportista', '0005_deportista_estatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Deportes.disciplina'),
        ),
    ]
