# Generated by Django 3.2.19 on 2024-03-26 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='idioma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pais',
            name='idioma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reglamento',
            name='idioma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tipoevento',
            name='idioma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
