# Generated by Django 3.2.19 on 2024-02-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
