# Generated by Django 3.2.19 on 2024-03-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0003_alter_disciplina_deporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
