# Generated by Django 3.2.19 on 2024-04-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0005_auto_20240326_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='idioma',
            field=models.CharField(default='es', max_length=255, verbose_name='Idioma'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='idioma',
            field=models.CharField(default='es', max_length=255, verbose_name='Idioma'),
        ),
    ]
