# Generated by Django 3.2.19 on 2024-03-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0003_auto_20240229_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlson',
            name='evaluacion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
