# Generated by Django 3.2.19 on 2024-04-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0005_rast_normalidad_potencia_maxima'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='idioma',
            field=models.CharField(default='es', max_length=255, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='prueba',
            name='idioma',
            field=models.CharField(default='es', max_length=255, verbose_name='Idioma'),
        ),
    ]
