# Generated by Django 3.2.19 on 2024-02-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='etapa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
