# Generated by Django 3.2.19 on 2024-03-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0004_carlson_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='rast',
            name='normalidad_potencia_maxima',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
