# Generated by Django 3.2.19 on 2024-03-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0004_alter_disciplina_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='deporte',
            name='idioma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='idioma',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
