# Generated by Django 3.2.19 on 2024-04-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0002_auto_20240326_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='pais',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='reglamento',
            name='idioma',
        ),
        migrations.RemoveField(
            model_name='tipoevento',
            name='idioma',
        ),
    ]
