# Generated by Django 3.2.19 on 2024-04-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomencladores', '0003_auto_20240415_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='idioma',
            field=models.CharField(default='es', max_length=255, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='reglamento',
            name='idioma',
            field=models.CharField(default='es', max_length=255, verbose_name='Idioma'),
        ),
        migrations.AddField(
            model_name='tipoevento',
            name='idioma',
            field=models.CharField(default='es', max_length=255, verbose_name='Idioma'),
        ),
    ]
